/**
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountInfo } from './accountInfo';


export interface AccountMetaData {
    cosignatories?: Array<AccountInfo>;
    cosignatoryOf?: Array<AccountInfo>;
    remoteStatus?: AccountMetaData.RemoteStatusEnum;
    status?: AccountMetaData.StatusEnum;
}
export namespace AccountMetaData {
    export type RemoteStatusEnum = 'REMOTE' | 'ACTIVATING' | 'ACTIVE' | 'DEACTIVATING' | 'INACTIVE';
    export const RemoteStatusEnum = {
        REMOTE: 'REMOTE' as RemoteStatusEnum,
        ACTIVATING: 'ACTIVATING' as RemoteStatusEnum,
        ACTIVE: 'ACTIVE' as RemoteStatusEnum,
        DEACTIVATING: 'DEACTIVATING' as RemoteStatusEnum,
        INACTIVE: 'INACTIVE' as RemoteStatusEnum
    }
    export type StatusEnum = 'UNKNOWN' | 'LOCKED' | 'UNLOCKED';
    export const StatusEnum = {
        UNKNOWN: 'UNKNOWN' as StatusEnum,
        LOCKED: 'LOCKED' as StatusEnum,
        UNLOCKED: 'UNLOCKED' as StatusEnum
    }
}
