/**
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Amount } from './amount';
import { BlockAmount } from './blockAmount';
import { KeyPair } from './keyPair';
import { MultisigInfo } from './multisigInfo';


export interface AccountInfo {
    address?: Address;
    balance?: Amount;
    importance?: number;
    keyPair?: KeyPair;
    label?: string;
    multisigInfo?: MultisigInfo;
    numHarvestedBlocks?: BlockAmount;
    vestedBalance?: Amount;
}
