/**
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PrivateKey } from './privateKey';
import { PublicKey } from './publicKey';


export interface KeyPair {
    privateKey?: PrivateKey;
    publicKey?: PublicKey;
}
