/**
 * Proximax P2P Storage REST API
 * Proximax P2P Storage REST API
 *
 * OpenAPI spec version: v0.0.1
 * Contact: proximax.storage@proximax.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { GenericResponseMessage } from '../model/genericResponseMessage';
import { NodeInfo } from '../model/nodeInfo';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class NodeService {

    protected basePath = 'http://demo-gateway.proximax.io';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Check if the Storage Node is up and running.
     * This endpoint is used to check if the P2P Storage Node instance is either alive or down.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public checkNodeUsingGET(observe?: 'body', reportProgress?: boolean): Observable<GenericResponseMessage>;
    public checkNodeUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GenericResponseMessage>>;
    public checkNodeUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GenericResponseMessage>>;
    public checkNodeUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<GenericResponseMessage>(`${this.basePath}/node/check`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Storage Node Information
     * This endpoint returns the information of the P2P Storage Node
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNodeInfoPeersUsingGET(observe?: 'body', reportProgress?: boolean): Observable<NodeInfo>;
    public getNodeInfoPeersUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NodeInfo>>;
    public getNodeInfoPeersUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NodeInfo>>;
    public getNodeInfoPeersUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<NodeInfo>(`${this.basePath}/node/info/peers`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Storage Node Information
     * This endpoint returns the information of the P2P Storage Node
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getNodeInfoUsingGET(observe?: 'body', reportProgress?: boolean): Observable<NodeInfo>;
    public getNodeInfoUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<NodeInfo>>;
    public getNodeInfoUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<NodeInfo>>;
    public getNodeInfoUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<NodeInfo>(`${this.basePath}/node/info`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Storage Node Information
     * This endpoint returns the information of the P2P Storage Node
     * @param network Blockchain Network
     * @param domain Blockchain Network Domain (xxx.xxx.xxx)
     * @param port Blockchain Network Port (xxx.xxx.xxx)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setBlockchainNodeConnectionUsingPOST(network: string, domain: string, port: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public setBlockchainNodeConnectionUsingPOST(network: string, domain: string, port: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public setBlockchainNodeConnectionUsingPOST(network: string, domain: string, port: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public setBlockchainNodeConnectionUsingPOST(network: string, domain: string, port: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (network === null || network === undefined) {
            throw new Error('Required parameter network was null or undefined when calling setBlockchainNodeConnectionUsingPOST.');
        }
        if (domain === null || domain === undefined) {
            throw new Error('Required parameter domain was null or undefined when calling setBlockchainNodeConnectionUsingPOST.');
        }
        if (port === null || port === undefined) {
            throw new Error('Required parameter port was null or undefined when calling setBlockchainNodeConnectionUsingPOST.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (network !== undefined) {
            queryParameters = queryParameters.set('network', <any>network);
        }
        if (domain !== undefined) {
            queryParameters = queryParameters.set('domain', <any>domain);
        }
        if (port !== undefined) {
            queryParameters = queryParameters.set('port', <any>port);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<string>(`${this.basePath}/node/set/blockchain/connection`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
